-- CreateEnum
CREATE TYPE "ProductionItemSource" AS ENUM ('AUTO', 'MANUAL');

-- AlterTable
ALTER TABLE "production_items" ADD COLUMN "source_type" "ProductionItemSource" NOT NULL DEFAULT 'MANUAL';

-- Classify production rows generated by the old dispatch-specific workflow as AUTO.
UPDATE "production_items" AS item
SET "source_type" = 'AUTO'
FROM "production_lists" AS list
WHERE item."production_list_id" = list."id"
  AND list."source_dispatch_id" IS NOT NULL;

-- CreateIndex
CREATE INDEX "production_items_source_type_idx" ON "production_items"("source_type");
